export const API_ENDPOINTS = {
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  CATEGORIES: "/categories",
  FEATURED_CATEGORIES: "/categories/featured",
  COLLECTIONS: "/collections",
  BRANDS: "/brands",
  PRODUCTS: "/products",
  FEATURED_PRODUCTS: "/products/featured",
  TOP_SELLER_PRODUCTS: "/products/top",
  ON_SELLING_PRODUCTS: "/products/sale",
  PRODUCT: "/product",
  RELATED_PRODUCTS: "/products/related",
  BEST_SELLER_PRODUCTS: "/products/top",
  NEW_ARRIVAL_PRODUCTS: "/products/new",
  FLASH_SALE_PRODUCTS: "/products/sale",
  SHOPS: "/shops",
  SHOP: "/shop",
  SEARCH: "/search",
  ORDERS: "/orders",
  ORDER: "/order",
};
