---

version: '3.3'

services:

  bytebase:
    image: bytebase/bytebase:0.13.0
    restart: always
    ports:
      - "9999:80database"
    volumes:
      - './docker/volumes/bytebase:/var/opt/bytebase'

  # metabase:
  #   image: metabase/metabase
  #   ports:
  #     - '7799:3000'
  #   volumes:
  #     - './docker/volumes/metabase:/metabase-data'
  #   environment:
  #     MB_DB_FILE: '/metabase-data/metabase.db'

  # clickhouse:
  #   # KEEP CLICKHOUSE-SERVER VERSION IN SYNC WITH
  #   # https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/templates/clickhouse_instance.yaml#L88
  #   image: yandex/clickhouse-server:21.6.5
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #   ports:
  #     - '8123:8123'
  #     - '9000:9000'
  #     - '9440:9440'
  #     - '9009:9009'
  #   volumes:
  #     - ./docker/volumes/clickhouse/idl:/idl
  #     - ./docker/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #     - ./docker/volumes/clickhouse/config.xml:/etc/clickhouse-server/config.xml
  #     - ./docker/volumes/clickhouse/users.xml:/etc/clickhouse-server/users.xml

  # zookeeper:
  #   image: wurstmeister/zookeeper
    
  # kafka:
  #   image: wurstmeister/kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: kafka
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  # web:
  #   container_name: posthog_web
  #   depends_on:
  #     - db
  #     - redis
  #     - clickhouse
  #     - kafka
  #   environment:
  #     DATABASE_URL: postgres://posthog:posthog@db:5432/posthog
  #     REDIS_URL: redis://redis:6379/
  #     KAFKA_URL: 'kafka://kafka'
  #     CLICKHOUSE_HOST: 'clickhouse'
  #     CLICKHOUSE_DATABASE: 'posthog'
  #     CLICKHOUSE_SECURE: 'false'
  #     CLICKHOUSE_VERIFY: 'false'
  #     SECRET_KEY: <randomly generated secret key>
  #     PGHOST: db
  #     PGUSER: posthog
  #     PGPASSWORD: posthog
  #   image: posthog/posthog:latest
  #   links:
  #     - db:db
  #     - redis:redis
  #     - clickhouse:clickhouse
  #     - kafka:kafka
  #   ports:
  #     - 8000:8000
  #     - 80:8000